from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from pathlib import Path

import httpx
from pydantic import BaseModel

from dashlet_framework import Provenance
from issuer_fixture import IssuerSnapshot, build_snapshot_from_live_json, load_snapshot

# SEC EDGAR requires a descriptive User-Agent identifying the requester --
# generic/absent User-Agent headers are rejected with 403. See
# https://www.sec.gov/os/webmaster-faq#developers
_USER_AGENT = "Canvas Dashlet Studio research tool (contact: navodit.kaushik@gmail.com)"
_TIMEOUT_SECONDS = 10.0

_TICKER_MAP_URL = "https://www.sec.gov/files/company_tickers.json"
_SUBMISSIONS_URL_TEMPLATE = "https://data.sec.gov/submissions/CIK{cik}.json"
_COMPANY_FACTS_URL_TEMPLATE = "https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json"


class ProviderError(Exception):
    def __init__(self, error_code: str, message: str) -> None:
        self.error_code = error_code
        self.message = message
        super().__init__(message)


class IssuerDataMode(str, Enum):
    FIXTURE = "fixture"
    LIVE = "live"


class IssuerSnapshotResult(BaseModel):
    snapshot: IssuerSnapshot
    provenance: Provenance


def _fetch_json(url: str) -> dict:
    try:
        with httpx.Client(timeout=_TIMEOUT_SECONDS, headers={"User-Agent": _USER_AGENT}) as client:
            response = client.get(url)
    except httpx.TimeoutException as exc:
        raise ProviderError("sec_timeout", f"Timed out fetching {url}") from exc
    except httpx.HTTPError as exc:
        raise ProviderError("sec_network_error", f"Network error fetching {url}: {exc}") from exc

    if response.status_code == 404:
        raise ProviderError("ticker_not_found", f"SEC EDGAR returned 404 for {url}")
    if response.status_code != 200:
        raise ProviderError("sec_fetch_error", f"HTTP {response.status_code} fetching {url}")
    return response.json()


class FixtureIssuerProvider:
    """Reads recorded, real SEC EDGAR data frozen into fixtures/issuer/.

    This is not synthetic/fictional data (unlike Treasury or Portfolio
    Exposure's fixtures) -- it is a real historical snapshot, generated by
    scripts/generate_issuer_fixtures.py from the same live SEC APIs
    PublicIssuerProvider calls, kept small and frozen purely so automated
    tests stay deterministic and network-free (see docs/DATA_ACCESS.md §6).
    """

    def __init__(self, fixture_dir: Path) -> None:
        self._fixture_dir = fixture_dir

    def list_available_tickers(self) -> list[str]:
        return sorted(path.stem for path in self._fixture_dir.glob("*.json"))

    def get_snapshot(self, ticker: str) -> IssuerSnapshotResult:
        path = self._fixture_dir / f"{ticker.upper()}.json"
        if not path.exists():
            raise ProviderError(
                "unknown_ticker",
                f"No recorded fixture for ticker: {ticker}. Available: {', '.join(self.list_available_tickers())}",
            )
        snapshot = load_snapshot(path)
        latest_period_end = max((p.period_end for p in snapshot.periods), default=None)
        provenance = Provenance(
            source="sec-edgar-recorded",
            source_url=None,
            observation_date=latest_period_end or snapshot.fixture_meta.recorded_at,
            retrieved_at=datetime.now(UTC),
            data_mode="fixture",
            is_stale=True,  # a frozen recorded snapshot is always potentially behind live SEC data
        )
        return IssuerSnapshotResult(snapshot=snapshot, provenance=provenance)


class PublicIssuerProvider:
    """Fetches real, current data directly from SEC EDGAR's public APIs for
    any of the ~10,388 SEC-registered tickers. No API key required; SEC
    requires a descriptive User-Agent (see _USER_AGENT above).
    """

    def __init__(self) -> None:
        self._ticker_cik_cache: dict[str, str] | None = None

    def _ticker_to_cik(self, ticker: str) -> str:
        if self._ticker_cik_cache is None:
            raw = _fetch_json(_TICKER_MAP_URL)
            self._ticker_cik_cache = {
                entry["ticker"].upper(): str(entry["cik_str"]).zfill(10) for entry in raw.values()
            }
        cik = self._ticker_cik_cache.get(ticker.upper())
        if cik is None:
            raise ProviderError("ticker_not_found", f"No SEC-registered company found for ticker: {ticker}")
        return cik

    def fetch_raw(self, ticker: str) -> tuple[str, dict, dict]:
        """Returns (cik, submissions_json, company_facts_json) without
        wrapping into an IssuerSnapshotResult. get_snapshot() uses this
        internally; scripts/generate_issuer_fixtures.py also calls it
        directly so fixture generation shares this exact fetch path rather
        than re-implementing it.
        """
        cik = self._ticker_to_cik(ticker)
        submissions = _fetch_json(_SUBMISSIONS_URL_TEMPLATE.format(cik=cik))
        company_facts = _fetch_json(_COMPANY_FACTS_URL_TEMPLATE.format(cik=cik))
        return cik, submissions, company_facts

    def get_snapshot(self, ticker: str) -> IssuerSnapshotResult:
        cik, submissions, company_facts = self.fetch_raw(ticker)

        snapshot = build_snapshot_from_live_json(
            submissions_json=submissions, company_facts_json=company_facts, data_mode="live"
        )
        if not snapshot.periods:
            raise ProviderError(
                "missing_financial_data",
                f"SEC EDGAR has no usable annual XBRL financial data for ticker: {ticker}",
            )

        latest_period_end = max(p.period_end for p in snapshot.periods)
        provenance = Provenance(
            source="sec-edgar-live",
            source_url=_COMPANY_FACTS_URL_TEMPLATE.format(cik=cik),
            observation_date=latest_period_end,
            retrieved_at=datetime.now(UTC),
            data_mode="live",
            is_stale=False,
        )
        return IssuerSnapshotResult(snapshot=snapshot, provenance=provenance)


def resolve_provider(
    data_mode: IssuerDataMode, fixture_dir: Path
) -> FixtureIssuerProvider | PublicIssuerProvider:
    if data_mode == IssuerDataMode.FIXTURE:
        return FixtureIssuerProvider(fixture_dir)
    if data_mode == IssuerDataMode.LIVE:
        return PublicIssuerProvider()
    raise ValueError(f"Unknown data_mode: {data_mode!r}. Expected 'fixture' or 'live'.")
